input:
  file:
    path: resources/input.jsonl

output:
  file:
    path: resources/output.jsonl

pipeline:
  processors:
    - json:
        operator: copy
        path: raw_links
        value: processed_links
    - process_field:
        codec: json
        path: processed_links
        processors:
          - type: coding_challenge
        result_type: array
